version: '3.8'
services:
  whisper-nonavx:
    container_name: whisper-nonavx
    build: .
    restart: unless-stopped
    ports:
      - "10300:8000"
    volumes:
      - /volume3/ai-stack/audio:/data
      - /volume3/ai-stack/models:/models
    environment:
      - WHISPER_MODEL=base
      - WHISPER_LANG=zh
      - WHISPER_THREADS=4
